---
title: "data_analysis_1"
output: html_document
date: "2024-06-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Chapter 5 example code

```{r gapminder}
library(gapminder)
library(tidyverse)

# display structure of element
str(gapminder) 

class(gapminder)
gapminder
names(gapminder)
ncol(gapminder)
dim(gapminder)
nrow(gapminder)
summary(gapminder)

head(gapminder$lifeExp)
summary(gapminder$lifeExp)
```

## Including Plots

```{r gapminder_lifexp plot, echo=FALSE}
hist(gapminder$lifeExp)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r gapminder year and continent}
# now for categorical year
summary(gapminder$year)
table(gapminder$year)


# categories stored as factor
class(gapminder$continent)
summary(gapminder$continent)
nlevels(gapminder$continent)

table(gapminder$continent)
```
```{r gapminder continent plot, echo=FALSE}
barplot(table(gapminder$continent))
```

